# -*- coding: utf-8 -*-
"""
Analyze downloaded media assets for provenance signals (C2PA) and fingerprints (PDQ/vPDQ).

Expected input: media_manifest.csv generated by p2p.runners.run_reddit_seed (or similar),
where each row contains at least media_url, posting_id, kind, and local_path.
"""
from __future__ import annotations

import argparse
import csv
from dataclasses import asdict
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from p2p.datasource.utils import write_jsonl
from p2p.provenance.fingerprint import FileFingerprints, fingerprints_for_path
from p2p.provenance.probes.c2pa_probe import analyze_one as c2pa_analyze


def build_argparser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(description="Run provenance probes (C2PA/PDQ/vPDQ) on downloaded media.")
    ap.add_argument("--manifest", required=True, help="Path to media_manifest.csv with local_path populated.")
    ap.add_argument(
        "--media-root",
        type=str,
        default=None,
        help="Base directory to resolve relative local_path values. Defaults to manifest directory.",
    )
    ap.add_argument(
        "--out-provenance",
        type=str,
        default=None,
        help="Output CSV path (default: <manifest_dir>/provenance_media.csv).",
    )
    ap.add_argument(
        "--emit-jsonl",
        action="store_true",
        help="Also write detailed provenance_media.jsonl alongside the CSV.",
    )
    ap.add_argument(
        "--jsonl-path",
        type=str,
        default=None,
        help="Override JSONL output path (requires --emit-jsonl).",
    )
    ap.add_argument(
        "--probes",
        type=str,
        default="c2pa,pdq,vpdq",
        help="Comma-separated probes to run. Supported: c2pa, pdq, vpdq.",
    )
    return ap


def load_manifest(path: Path) -> List[Dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        rows = [dict(row) for row in reader]
    return rows


def resolve_local_path(local_path: str, media_root: Path) -> Optional[Path]:
    if not local_path:
        return None
    lp = Path(local_path)
    if lp.is_absolute():
        return lp if lp.exists() else None
    candidate = media_root / lp
    return candidate if candidate.exists() else None


def analyze_path(
    path: Path,
    run_c2pa: bool,
    run_pdq: bool,
    run_vpdq: bool,
) -> Tuple[Optional[dict], Optional[FileFingerprints]]:
    c2pa_result: Optional[dict] = None
    fp_result: Optional[FileFingerprints] = None

    if run_c2pa:
        report = c2pa_analyze(str(path))
        c2pa_result = asdict(report)

    if run_pdq or run_vpdq:
        fp_result = fingerprints_for_path(str(path))

    return c2pa_result, fp_result


def format_row(
    manifest_row: Dict[str, str],
    local_path: str,
    exists: bool,
    c2pa_res: Optional[dict],
    fp_res: Optional[FileFingerprints],
) -> Dict[str, str]:
    row = {
        "posting_id": manifest_row.get("posting_id", ""),
        "media_url": manifest_row.get("media_url", ""),
        "kind": manifest_row.get("kind", ""),
        "content_type": manifest_row.get("content_type", ""),
        "local_path": local_path,
        "exists": "1" if exists else "0",
        "c2pa_present": "",
        "c2pa_valid": "",
        "c2pa_vendor": "",
        "c2pa_claim_generator": "",
        "c2pa_assertions": "",
        "c2pa_error": "",
        "pdq_available": "",
        "pdq_hash": "",
        "pdq_quality": "",
        "pdq_error": "",
        "vpdq_available": "",
        "vpdq_frames": "",
        "vpdq_error": "",
        "tmk_path": "",
        "fingerprint_errors": "",
    }

    if c2pa_res:
        row["c2pa_present"] = _bool_to_str(c2pa_res.get("present"))
        row["c2pa_valid"] = _bool_to_str(c2pa_res.get("valid"))
        row["c2pa_vendor"] = _safe_str(c2pa_res.get("vendor"))
        row["c2pa_claim_generator"] = _safe_str(c2pa_res.get("claim_generator"))
        row["c2pa_assertions"] = _safe_str(c2pa_res.get("assertions_count"))
        row["c2pa_error"] = _safe_str(c2pa_res.get("error"))

    if fp_res:
        if fp_res.pdq:
            row["pdq_available"] = _bool_to_str(fp_res.pdq.available)
            row["pdq_hash"] = _safe_str(fp_res.pdq.hash_hex)
            row["pdq_quality"] = _safe_str(fp_res.pdq.quality)
            row["pdq_error"] = _safe_str(fp_res.pdq.error)
        else:
            row["pdq_available"] = ""
        if fp_res.vpdq:
            row["vpdq_available"] = _bool_to_str(fp_res.vpdq.available)
            frames = fp_res.vpdq.frames or []
            row["vpdq_frames"] = str(len(frames))
            row["vpdq_error"] = _safe_str(fp_res.vpdq.error)
        else:
            row["vpdq_available"] = ""
        row["tmk_path"] = _safe_str(fp_res.tmk_path)
        if fp_res.errors:
            row["fingerprint_errors"] = ";".join(sorted(set(e for e in fp_res.errors if e)))

    return row


def _safe_str(value) -> str:
    if value is None:
        return ""
    return str(value)


def _bool_to_str(value: Optional[bool]) -> str:
    if value is None:
        return ""
    return "1" if value else "0"


def main():
    ap = build_argparser()
    args = ap.parse_args()

    manifest_path = Path(args.manifest).resolve()
    manifest_rows = load_manifest(manifest_path)
    manifest_dir = manifest_path.parent
    media_root = Path(args.media_root).resolve() if args.media_root else manifest_dir

    probes = {p.strip().lower() for p in args.probes.split(",") if p.strip()}
    run_c2pa = "c2pa" in probes
    run_pdq = "pdq" in probes
    run_vpdq = "vpdq" in probes

    out_csv = Path(args.out_provenance) if args.out_provenance else manifest_dir / "provenance_media.csv"
    out_csv.parent.mkdir(parents=True, exist_ok=True)

    jsonl_path: Optional[Path] = None
    if args.emit_jsonl:
        jsonl_path = Path(args.jsonl_path) if args.jsonl_path else out_csv.with_suffix(".jsonl")

    results: List[Dict[str, str]] = []
    jsonl_records: List[Dict[str, object]] = []

    cache: Dict[str, Tuple[Optional[dict], Optional[FileFingerprints]]] = {}

    for row in manifest_rows:
        local_path = row.get("local_path", "") or ""
        resolved = resolve_local_path(local_path, media_root)
        cache_key = str(resolved) if resolved else ""

        c2pa_res: Optional[dict] = None
        fp_res: Optional[FileFingerprints] = None
        exists = resolved is not None

        if resolved:
            if cache_key not in cache:
                cache[cache_key] = analyze_path(resolved, run_c2pa, run_pdq, run_vpdq)
            c2pa_res, fp_res = cache[cache_key]

        formatted = format_row(row, local_path, exists, c2pa_res, fp_res)
        results.append(formatted)

        if jsonl_path:
            payload = {
                "media_manifest": row,
                "analysis": {
                    "local_exists": exists,
                    "c2pa": c2pa_res,
                    "fingerprints": asdict(fp_res) if (fp_res and hasattr(fp_res, "__dict__")) else None,
                },
            }
            jsonl_records.append(payload)

    fieldnames = [
        "posting_id",
        "media_url",
        "kind",
        "content_type",
        "local_path",
        "exists",
        "c2pa_present",
        "c2pa_valid",
        "c2pa_vendor",
        "c2pa_claim_generator",
        "c2pa_assertions",
        "c2pa_error",
        "pdq_available",
        "pdq_hash",
        "pdq_quality",
        "pdq_error",
        "vpdq_available",
        "vpdq_frames",
        "vpdq_error",
        "tmk_path",
        "fingerprint_errors",
    ]

    with out_csv.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for r in results:
            writer.writerow({k: r.get(k, "") for k in fieldnames})

    if jsonl_path:
        write_jsonl(str(jsonl_path), jsonl_records)

    print(f"[provenance] analyzed {len(results)} rows -> {out_csv}")
    if jsonl_path:
        print(f"  - detailed jsonl: {jsonl_path}")


if __name__ == "__main__":
    main()
